version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins-custom
    image: jenkins-with-docker:latest
    container_name: jenkins
    user: root                      # corre el proceso como root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # Mount del named pipe de Docker Desktop de Windows
      - //./pipe/docker_engine:/var/run/docker.sock
    restart: unless-stopped

  web:
    build:
      context: ./simple-web
    image: simple-web:latest
    container_name: simple-web
    ports:
      - "8081:80"
    restart: unless-stopped
